### PR TITLE
Correct conditional get logic (prevent a 304 on etag mismatch)

### PR DESCRIPTION
**Pull request by melmothx**
If both etag and last-modified are present, check if both match

From https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.3.4

An HTTP/1.1 origin server, upon receiving a conditional request that includes
both a Last-Modified date (e.g., in an If-Modified-Since or If-Unmodified-Since
header field) and one or more entity tags (e.g., in an If-Match, If-None-Match,
or If-Range header field) as cache validators, MUST NOT return a response
status of 304 (Not Modified) unless doing so is consistent with all of the
conditional header fields in the request.

### CODE REVIEW

**Comment by miyagawa** [comment]
i believe that the new behavior is correct but that nested if's are ugly and repetitive. There should be a shorter and cleaner way to write it.

**Comment by melmothx** [comment]
The nested if can be postfixed, but honestly don't know which difference can do. I think I did my part pointing to the bug, adding tests and providing working code. I'll leave cosmetics to others. Cheers

**Comment by miyagawa** [comment]
>  don't know which difference can do

It makes maintaining the code less of a problem.

**Comment by miyagawa** [comment]
Added some cleanup in #569

**Pull request closed without merging**
