### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KES777**
test

### CODE REVIEW

**Comment by KES777** [comment]
```
$app =  builder {
    enable 'Lint';
    enable 'Session', store => 'File';
};
```
I got error:
`Can't use string ("2") as a subroutine ref while "strict refs"`

```
Sun Aug 30 17:50:08 2015 - Sun Aug 30 17:50:08 2015 - *** uWSGI perl stacktrace ***
Sun Aug 30 17:50:08 2015 - Trace begun at (eval 98) line 1
eval 'Devel::StackTrace->new->as_string;' at /home/kes/perl5/lib/perl5/Plack/Middleware/Session.pm line 53
Plack::Middleware::Session::call('Plack::Middleware::Session=HASH(0x2be7298)', 'HASH(0x1424eb0)') called at /home/kes/perl5/lib/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x1424eb0)') called at /home/kes/perl5/lib/perl5/Plack/Middleware/Lint.pm line 24
Plack::Middleware::Lint::call('Plack::Middleware::Lint=HASH(0x2c36048)', 'HASH(0x1424eb0)') called at /home/kes/perl5/lib/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x1424eb0)') called at (eval 98) line 0
eval {...} at (eval 98) line 0
Sun Aug 30 17:50:08 2015 - *** end of perl stacktrace ***
```

**Comment by miyagawa** [comment]
You need $app to apply middleware to. See perldoc Plack::Builder.

**Comment by KES777** [comment]
yes, I know, But Lint does not check nothing in this case. It must be closer to $app. Then it done its work:
```
$app =  builder {
    enable 'Session', store => 'File';
    enable 'Lint';
};
```

```
un Aug 30 18:15:22 2015 - PSGI app should be a code reference: 2 at /home/kes/perl5/lib/perl5/Plack/Middleware/Lint.pm line 13, <DATA> line 46.
```

**Comment by miyagawa** [comment]
No, it can't check that.

**Comment by KES777** [comment]
There just a note in doc https://github.com/KES777/Plack/commit/d8c5cf6504e38f5cfb0f880e7b96d0ba81cd60e8
So I close merge request

**Comment by KES777** [comment]
Can we speak in chat?

**Comment by miyagawa** [comment]
You can come over to #plack on irc.perl.org. I will be traveling for a week and might not be available for most of the time, but there are many people on the channel who can help.

**Comment by KES777** [comment]
I do not need help. I just want to speak about why >it can't check that.

I supply two builder's and get two error messages. last one is expected. So I contribute to doc about that **'Lint' must be closer to $app**

**Comment by miyagawa** [comment]
because Lint can only check the PSGI app that it directly wraps. `enable` gives a valid PSGI code ref that wraps another code ref, in which case is undef, which explodes in a later runtime.

**Comment by miyagawa** [comment]
"Lint must be closer to $app" is not a generally valid statement. It can only check what's inside Lint, if you put in the outermost, you can check if the middleware applied to the app doesn't return invalid response, and that's more generally reasonable and recommended way to put it.

You're right that this way Lint can't check if you put a valid PSGI app code ref, but that's a very basic error you'll be able to figure out in other way.

**Comment by miyagawa** [comment]
there's a technical reason it can't check certain things, and if you want more explanation you can either dive into the source code or ask on #plack. That's all I can offer.

**Comment by KES777** [comment]
You think [this](https://github.com/KES777/Plack/commit/d8c5cf6504e38f5cfb0f880e7b96d0ba81cd60e8) is useless?

**Comment by miyagawa** [comment]
Yeah, that's not a valid statement. As stated above, it can check certain things (i.e. if the $app is a valid ref) when it's closer to the app, but won't be able to validate other things that way. It's a trade off but in general I think Lint should be in the outer most.

**Comment by KES777** [comment]
**But it do its job even in this case:**
```
builder {
    enable 'Lint';
};
```
`Sun Aug 30 18:27:10 2015 - PSGI app should be a code reference: 1 at /home/kes/perl5/lib/perl5/Plack/Middleware/Lint.pm line 13, <DATA> line 46.`

but in this case it is **useless** (I get wrong error message)
```
builder {
    enable 'Lint';
    enable 'Session';
};
```
and again he **do its job** (I get right error message: *PSGI app should be a code reference*)
```
builder {
    enable 'Session';
    enable 'Lint';
};
```

Pay attantion where `enable 'Lint'` is situated

**Comment by miyagawa** [comment]
I'm saying that for the specific error (app being not a code ref) yes, but
for other request/response validation it is better set on the outer.

**Pull request closed without merging**
