### PR TITLE
Allow passing custom formatters to Plack::Middleware::AccessLog

### PR DESCRIPTION
**Pull request by frioux**

### CODE REVIEW

**Comment by miyagawa** [comment]
I would make `char_handlers` and `block_handlers` as a top level parameters rather than having them inside `formatters` but i guess that's a personal taste?

**Comment by miyagawa** [comment]
Other than that it looks pretty trivial and good.

**Comment by frioux** [comment]
I'll change it; if anyone's taste should I would think you would be that person.

**Comment by frioux** [comment]
done

**Comment by miyagawa** [comment]
Thanks. cc @kazeburo

**Comment by miyagawa** [comment]
@kazeburo any thoughts on this change?

**Comment by kazeburo** [comment]
:+1:

**Pull request merged**
