### PR TITLE
Feature/doc contribution

### PR DESCRIPTION
**Pull request by KES777**
discussion starts [here](https://github.com/plack/Plack/pull/520)

### CODE REVIEW

**Comment by miyagawa** [comment]
Can you remove the Lint.pm patch? As stated elsewhere, that is not always right. If you remove that part I'll merge it with a bit of fixes.

**Comment by miyagawa** [comment]
cherry picked with d0958703682736c063071995a59fac5fe0cd4830

**Comment by KES777** [comment]
as you ask [done](https://github.com/plack/Plack/pull/525)

**Comment by miyagawa** [comment]
never mind, it's already cherry picked.

**Pull request closed without merging**
